#!/usr/bin/env bash
# install-novnc-bridge.sh
#
# Bridges macOS Screen Sharing (the built-in VNC/RFB server on port 5900)
# through websockify to noVNC, so the remote-reauth link session_watchdog.py
# sends over Telegram can be opened directly in a phone browser — no VNC app
# install needed. Bound explicitly to this Mac's personal-Tailscale interface
# IP, resolved fresh on every start; refuses to bind 0.0.0.0 or any public
# interface if Tailscale isn't up.
#
# Prerequisites this script will NOT do for you (system/account settings):
#   1. Enable Screen Sharing: System Settings > General > Sharing > Screen Sharing
#   2. Install + log in to your OWN personal Tailscale (both this Mac and your
#      phone joined to the same tailnet) — separate from any other tailscaled
#      instance already running on this machine for an unrelated tunnel.
#
# Usage:
#   bash scripts/install-novnc-bridge.sh
#
# Uninstall:
#   bash scripts/install-novnc-bridge.sh --uninstall

set -euo pipefail

BRIDGE_DIR="$HOME/Library/Application Support/ai-command-center/novnc-bridge"
NOVNC_DIR="$BRIDGE_DIR/novnc"
RUN_SCRIPT="$BRIDGE_DIR/run-bridge.sh"
PLIST="$HOME/Library/LaunchAgents/com.jobagent.novnc-bridge.plist"
LOG_DIR="$HOME/Library/Logs/jobagent-novnc-bridge"

if [[ "${1:-}" == "--uninstall" ]]; then
  launchctl unload "$PLIST" 2>/dev/null || true
  rm -f "$PLIST" "$RUN_SCRIPT"
  echo "Uninstalled noVNC bridge (left $NOVNC_DIR and logs in place)."
  exit 0
fi

mkdir -p "$BRIDGE_DIR" "$LOG_DIR"

# ── noVNC static assets ───────────────────────────────────────────────────
if [[ ! -d "$NOVNC_DIR" ]]; then
  echo "Cloning noVNC into $NOVNC_DIR ..."
  git clone --depth 1 https://github.com/novnc/noVNC.git "$NOVNC_DIR"
else
  echo "noVNC already present at $NOVNC_DIR — skipping clone."
fi

# ── websockify ────────────────────────────────────────────────────────────
if ! python3 -c "import websockify" >/dev/null 2>&1; then
  echo "Installing websockify ..."
  pip3 install --user --quiet websockify
fi
WEBSOCKIFY_BIN="$(python3 -c "import shutil,sys; p=shutil.which('websockify'); print(p or '')")"
if [[ -z "$WEBSOCKIFY_BIN" ]]; then
  # pip --user installs land here on this machine's Python; not on PATH by default.
  WEBSOCKIFY_BIN="$HOME/Library/Python/3.12/bin/websockify"
fi
if [[ ! -x "$WEBSOCKIFY_BIN" ]]; then
  echo "Error: could not locate the websockify executable after install." >&2
  exit 1
fi

# ── Runtime wrapper: resolve the Tailscale IP fresh on every start ──────────
cat > "$RUN_SCRIPT" <<RUNSCRIPT
#!/usr/bin/env bash
# Auto-generated by install-novnc-bridge.sh — resolves this Mac's personal
# Tailscale IPv4 address at start and binds websockify ONLY to that address.
# Never falls back to 0.0.0.0 or a LAN-facing interface: if Tailscale isn't
# up, this exits non-zero instead of exposing the bridge more broadly.
set -euo pipefail

resolve_ts_ip() {
  for bin in \\
    "\${TAILSCALE_BIN:-}" \\
    "/Applications/Tailscale.app/Contents/MacOS/Tailscale" \\
    "/opt/homebrew/bin/tailscale" \\
    "/usr/local/bin/tailscale" \\
    "tailscale"
  do
    [[ -z "\$bin" ]] && continue
    if ip="\$("\$bin" ip -4 2>/dev/null | head -1)" && [[ -n "\$ip" ]]; then
      echo "\$ip"
      return 0
    fi
  done
  return 1
}

TS_IP="\$(resolve_ts_ip || true)"
if [[ -z "\$TS_IP" ]]; then
  echo "\$(date -u +%FT%TZ) ERROR: could not resolve a personal-Tailscale IPv4 address — refusing to bind a public/LAN interface. Is Tailscale installed and logged in?" >&2
  exit 1
fi

PORT="\${NOVNC_PORT:-6080}"
echo "\$(date -u +%FT%TZ) INFO: binding noVNC bridge to \$TS_IP:\$PORT -> localhost:5900"
exec "$WEBSOCKIFY_BIN" --web="$NOVNC_DIR" "\$TS_IP:\$PORT" localhost:5900
RUNSCRIPT
chmod +x "$RUN_SCRIPT"

# ── launchd plist ─────────────────────────────────────────────────────────
cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.jobagent.novnc-bridge</string>
  <key>ProgramArguments</key>
  <array>
    <string>$RUN_SCRIPT</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>30</integer>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/stdout.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/stderr.log</string>
</dict>
</plist>
PLIST

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo ""
echo "noVNC bridge installed and loaded."
echo "  It will refuse to bind anything until your personal Tailscale is up"
echo "  and Screen Sharing is enabled (System Settings > General > Sharing)."
echo "  Logs: $LOG_DIR"
echo "  Check status: launchctl list com.jobagent.novnc-bridge"
